import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import your Top Navigation component here
import TopNav from "@/components/shared/TopNav";

const geistSans = Geist({
variable: "--font-geist-sans",
subsets: ["latin"],
});

const geistMono = Geist_Mono({
variable: "--font-geist-mono",
subsets: ["latin"],
});

export const metadata: Metadata = {
title: "Create Next App",
description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{
children: React.ReactNode;
}>) {
return (
<html
lang="en"
className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
>
  <body>


    {/* Render the consistent TopNav globally on every page */}
    {/* <TopNav /> */}
    
    {/* The rest of your pages render inside {children} */}
    <main className="flex-1">
      {children}
    </main>
    
  </body>
</html>


);
}